package com.gottlieb.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class QuoteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuoteAllPropertiesEquals(Quote expected, Quote actual) {
        assertQuoteAutoGeneratedPropertiesEquals(expected, actual);
        assertQuoteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuoteAllUpdatablePropertiesEquals(Quote expected, Quote actual) {
        assertQuoteUpdatableFieldsEquals(expected, actual);
        assertQuoteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuoteAutoGeneratedPropertiesEquals(Quote expected, Quote actual) {
        assertThat(expected)
            .as("Verify Quote auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuoteUpdatableFieldsEquals(Quote expected, Quote actual) {
        assertThat(expected)
            .as("Verify Quote relevant properties")
            .satisfies(e -> assertThat(e.getIdentifier()).as("check identifier").isEqualTo(actual.getIdentifier()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(actual.getLastModifiedBy()))
            .satisfies(e -> assertThat(e.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(actual.getLastModifiedDate()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuoteUpdatableRelationshipsEquals(Quote expected, Quote actual) {
        // empty method
    }
}
